### ISSUE TITLE
mixed keys are not allowed

### ISSUE THREAD

**Issue by jsbain** [controversial/livejson#2]
consider, e.g.

```
import livejson
d=Database('test')
d['1']='foo'
d[1] = 'bar'
print(d)
```

You might consider a yaml backend.  Or a warning.

**Comment by controversial** [comment]
Huh, is that an issue with JSON, or me? And is it only an issue for jets that are identical?

**Comment by controversial** [comment]
Perhaps more concerning is that `livejson.Database` won't recall numeric keys

```
>>> import livejson
>>> a = livejson.Database('a.json')
>>> a[0] = 1
>>> a[0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/mobile/Containers/Shared/AppGroup/DF424212-8D52-48D1-8D11-76FBF7651F4C/Pythonista3/Documents/site-packages/livejson.py", line 39, in __getitem__
    out = self.data[key]
KeyError: 0
```

Perhaps `livejson` should fail altogether on non-numeric keys? It could try to be "smart" and remember the type of inputted keys, but that would have to be entirely in-memory and therefore not sustainable. 

Unless you see a better way, I think I'll go with throwing an error about how keys must be strings.

**Comment by wgaylord** [comment]
I could come up with a way for this to work. But it would probably be messy...

**Comment by controversial** [comment]
I don't really want to get into manipulating data (like `"1"` -> `"_int_1"`), because then it's no longer "just" the user's data, and we lose compatibility with other parsers to a detain degree. I also don't want to have something like a top-level `"_livejson"` key that stores lots of hidden data, for the same reason. 

I think it's fine for `livejson` only to store string keys and error otherwise, because that's all JSON supports. AFAIK, the integer storage, etc. is a "bonus feature" which we don't need to support. If JSON only officially supports strings, that's all we need to support here. 

@ywangd Do you think it'd be a good idea to have other repos for versions of this project with different storage back ends? I could also create a "livedata" repo which would implement classes for JSON, YAML, and more, but I kind of like this one 😛

**Comment by controversial** [comment]
So basically, error throwing is my current plan. I'll close this as soon as I implement it.

**Comment by wgaylord** [comment]
Okay.

**Comment by ywangd** [comment]
I think you meant to at jsbain?
Anyway, didn't know about this project and it looks pretty cool. As for the numeric key, I agree that it should just throw an error as livejson is still JSON. So follow the principle of least surprise, it should behave as JSON. 

Another minor suggestion: Most database modules allow user to specify whether it should auto-commit changes (many does by default). So maybe livejson could also implement this feature?

**Comment by controversial** [comment]
Yes, I did mean @jsbain , sorry. I agree, though. As far as turning "live" updates on and off, I don't think I'll do this, since no caching at all is currently used. Maybe if you have a compelling use case I'd consider it.

**Comment by controversial** [comment]
The fix is now on PyPI (I forgot to upload before)

**Comment by jsbain** [comment]
i meant use a liveyaml.  yaml is a much better fit for representing  python data.  json is a sort of subset of yaml

**Comment by controversial** [comment]
@jsbain I'll put that in a separate repo. I suspect the code will be largely the same, with only minor modifications, however I've never used YAML.

**Comment by controversial** [comment]
Looks like there's no stdlib support for YAML, so it looks like a `liveyaml` would need to involve third-party dependencies. I'll look into it, though.

**Comment by jsbain** [comment]
Oh you are right... I thought it was in the stdlib.  Really my point was there might be some surprising things with json, if the point is to emulate a dict.   Throwing an exception for types that cannot be stored is a good alternative.

**Comment by controversial** [comment]
Ok. I'll see whether we run into more problems later.

**Comment by controversial** [comment]
@ywangd FWIW your thing has been implemented and more in this department is coming soon.
